name: GlobalHackWeekDataWeek
version: '${project.version}'
main: me.agentxman.globalhackweekdataweek.GlobalHackWeekDataWeek
api-version: 1.20
authors: [ agentxman ]
description: a plugin for global hack week
commands:
  map:
    description: make a map out of the image